### ISSUE TITLE
Add support for Caddyfile

### ISSUE THREAD

**Issue by eman1986** [allape/IDEA-Caddyfile-plugin#1]
Appreciate the plugin, one nice addition would be the plugin to detect a caddy file that's named `Caddyfile` instead of just looking for any file that has `.Caddyfile`.

**Comment by allape** [comment]
Thanks for reporting this issue, I will work on this today 😄

**Comment by allape** [comment]
JetBrains is reviewing v0.2.0 update, but here is the zip file on GitHub: https://github.com/allape/IDEA-Caddyfile-plugin/releases/tag/v0.2.0

**Comment by eman1986** [comment]
wow! that was a fast turnaround, thanks for the prompt response.
