### ISSUE TITLE
Misinterpreted global block

### ISSUE THREAD

**Issue by amadeusmz** [allape/IDEA-Caddyfile-plugin#2]
Looks like the plugin can't understand the global block, which have no option id before the `{`

![image](https://github.com/user-attachments/assets/aff49654-7969-4cae-a683-a2a3dfc68e3c)

**Comment by allape** [comment]
Thanks for reporting this issue, I will add the language support for this syntax in the future version.

**Comment by allape** [comment]
This update should fix this, but I will test it more before uploading it to JetBrains Marketplace 😂.

https://github.com/allape/IDEA-Caddyfile-plugin/releases/tag/v0.3.0
